filebeat:
  prospectors:
    -
      paths:
        - "/logs/mig/mig-audit.log"
      document_type: mig-audit
      encoding: utf-8
      fields:
        instance_id: docker
    -
      paths:
        - "/logs/mig/mig-errors.log"
      document_type: mig-error
      multiline:
        pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}\ '
        negate: true
        match: after
      encoding: utf-8
      fields:
        instance_id: docker
    -
      paths:
        - /logs/mig/mig-calls.log
      encoding: utf-8
      input_type: log
      fields:
       instance_id: docker
      document_type: mig-calls
      max_bytes: 5000000
      multiline:
        pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}\ '
        negate: true
        match: after
        max_lines: 5000


output:
  logstash:
    enabled: true
    hosts: ["logstash-metrics:5044"]

shipper:

logging:
  level: debug
  to_syslog: false
  to_files: false
